# Generated by Django 4.0.3 on 2022-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session_current_experiment_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='private_chat',
            field=models.BooleanField(default=True, verbose_name='Private Chat'),
        ),
    ]
