# Generated by Django 4.0.3 on 2022-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parameterset_private_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'ordering': ['id'], 'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='id_label',
            field=models.CharField(default='1', max_length=2, verbose_name='ID Label'),
        ),
    ]
