# Generated by Django 4.1.3 on 2022-11-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parameterset_survey_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='survey_complete',
            field=models.BooleanField(default=False, verbose_name='Survey Complete'),
        ),
    ]
