# Generated by Django 4.1.3 on 2022-11-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_session_current_experiment_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Student ID'),
        ),
    ]
