# Generated by Django 4.1.3 on 2022-11-22 21:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_sessionplayer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='json_for_session',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
