# Generated by Django 4.1.3 on 2022-11-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_parametersetplayer_player_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'ordering': ['player_number'], 'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='json_index',
            field=models.IntegerField(default=0, verbose_name='Parameter set json index'),
        ),
    ]
