# Generated by Django 4.1.3 on 2022-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_parametersetplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='json_for_subject_update_required',
            field=models.BooleanField(default=False, verbose_name='Update json for subject required'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='json_for_subject_update_required',
            field=models.BooleanField(default=False, verbose_name='Update json for subject required'),
        ),
    ]
