# Generated by Django 4.1.7 on 2023-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_parameterset_json_for_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='post_forward_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='After Study Forwarding Link'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='prolific_mode',
            field=models.BooleanField(default=False, verbose_name='Prolific Mode'),
        ),
    ]
