# Generated by Django 4.1.7 on 2023-04-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_parameterset_post_forward_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='post_forward_link',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='prolific_completion_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Forward to Prolific after sesison'),
        ),
    ]
