# Generated by Django 4.1.7 on 2023-04-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_parameterset_post_forward_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='reconnection_limit',
            field=models.IntegerField(default=25, verbose_name='Age Warning'),
        ),
    ]
